name: dunbeholden
description: "Dunbeholden"

publish_to: 'none' 

version: 1.3.1+9

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  flutter_riverpod: ^2.3.6
  
  cached_network_image: ^3.3.1
  sqflite: ^2.3.2
  path_provider: ^2.0.15
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  table_calendar: ^3.0.0
  intl: ^0.17.0  
  logger: ^2.4.0
  provider: ^6.1.2
  flutter_native_splash: ^2.4.1
  video_player: ^2.2.19
  font_awesome_flutter: ^10.1.0
  shared_preferences: ^2.3.5
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.1.14
  
  # flutter_sound: ^9.2.13
  flutter_cache_manager: ^3.3.1
  connectivity_plus: ^6.1.1
  flutter_local_notifications: ^17.2.1
  firebase_performance: ^0.9.4+7
  firebase_crashlytics: ^3.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8
  flutter_lints: ^4.0.0
  fake_cloud_firestore: ^2.4.8
  network_image_mock: ^2.1.1
  fake_async: ^1.3.1
  url_launcher_platform_interface: ^2.0.3


flutter:
  uses-material-design: true

  assets:
  # icons
    - assets/icons/apple.png
    - assets/icons/google.png
    - assets/icons/facebook.png
    - assets/icons/dunbeholden.png
    - assets/icons/db_circle.png
  

  # images
    - assets/images/default_player.png
    - assets/images/shop_banner.jpg

   
