name: dunbeholden
description: "Dunbeholden"

publish_to: 'none' 

version: 1.0.2+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  flutter_riverpod: ^2.3.6
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.2.1
  carousel_slider: ^4.2.1
  intl: ^0.18.1
  shared_preferences: ^2.3.4
  logger: ^2.5.0
  permission_handler: ^11.3.1
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  # icons
    - assets/icons/apple.png
    - assets/icons/google.png
    - assets/icons/facebook.png
    - assets/icons/dunbeholden.png
    - assets/icons/dunbeholden_white.png
    - assets/icons/waterhouse.png
    - assets/icons/hvfc.png
    - assets/icons/lhcc.png
    - assets/icons/cavalier.png
    - assets/icons/humble.png
    - assets/icons/db_circle.png
    - assets/icons/premier_league_logo.png
    - assets/icons/molynes.png

  # images
    - assets/images/d1.png
    - assets/images/d2.png
    - assets/images/150x150.png
    - assets/images/default_player.png
    - assets/images/dunbeholden.png
    - assets/images/arnett-gardens-fc-logo.png
    - assets/images/home_jersey.png
    - assets/images/home_jersey_back.png
    - assets/images/3-3.png
    - assets/images/charity-match.jpg

    # staff
    - assets/staff/donavan-witter.jpg
    - assets/staff/oneisho-goode.jpg
    - assets/staff/vivian-matthews.jpg
    - assets/staff/judith-drummond.jpg
    - assets/staff/roger-simmonds.jpeg

  # players
    - assets/images/players/ajuma_johnson.jpg
    - assets/images/players/chantomoi_taylor.jpg
    - assets/images/players/chevoy_watkin.jpg
    - assets/images/players/dean-andre_thomas.jpg
    - assets/images/players/donovan_segree.jpg
    - assets/images/players/dwight_merrick.jpg
    - assets/images/players/fabion_maccarthy.jpg
    - assets/images/players/fakibi_farquharson.jpg
    - assets/images/players/gerald_jr_neil.jpg
    - assets/images/players/leo_campbell.jpg
    - assets/images/players/malachi_douglas.jpg
    - assets/images/players/nakeel_wright.jpg
    - assets/images/players/neron_barrow.jpg
    - assets/images/players/ricardo_thomas.jpg
    - assets/images/players/saneekie_burton.jpg
    - assets/images/players/shakeen_powell.jpg
    - assets/images/players/tyrese_gowe.jpg
