// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM7UrAuldD2DFDF-IpzKVXMxZ2PqcfghY',
    appId: '1:295450309393:web:5a0cf7af971559fc0012b0',
    messagingSenderId: '295450309393',
    projectId: 'schoolapp-feed2',
    authDomain: 'schoolapp-feed2.firebaseapp.com',
    storageBucket: 'schoolapp-feed2.appspot.com',
    measurementId: 'G-P9GG4F52SK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA79QRA45vdCGq48LD65LhAjDulNByhPIU',
    appId: '1:295450309393:android:9be2271f0f1824c60012b0',
    messagingSenderId: '295450309393',
    projectId: 'schoolapp-feed2',
    storageBucket: 'schoolapp-feed2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC6WWIuO1Ep5cHYC4E-lDN4e35lL2KFe4',
    appId: '1:295450309393:ios:0a5a442b4c73cb750012b0',
    messagingSenderId: '295450309393',
    projectId: 'schoolapp-feed2',
    storageBucket: 'schoolapp-feed2.appspot.com',
    iosBundleId: 'com.example.schoolapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC6WWIuO1Ep5cHYC4E-lDN4e35lL2KFe4',
    appId: '1:295450309393:ios:0a5a442b4c73cb750012b0',
    messagingSenderId: '295450309393',
    projectId: 'schoolapp-feed2',
    storageBucket: 'schoolapp-feed2.appspot.com',
    iosBundleId: 'com.example.schoolapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM7UrAuldD2DFDF-IpzKVXMxZ2PqcfghY',
    appId: '1:295450309393:web:6f2068839e037ef50012b0',
    messagingSenderId: '295450309393',
    projectId: 'schoolapp-feed2',
    authDomain: 'schoolapp-feed2.firebaseapp.com',
    storageBucket: 'schoolapp-feed2.appspot.com',
    measurementId: 'G-J6EZ4JZ7CV',
  );
}
